modLoader="javafml"
loaderVersion="[45,)"
license='All Rights Reserved'

[[mods]]
modId="greenthumbs"
version="${file.jarVersion}"
displayName="Green Thumbs"
credits=""
authors="cfrishausen"
description='''
Test your hand at growing and developing your own crop strains.
'''
[[dependencies.greenthumbs]]
modId="forge"
mandatory=true
versionRange="[45,)"
ordering="NONE"
side="BOTH"
[[dependencies.greenthumbs]]
modId="minecraft"
mandatory=true
versionRange="[1.19.4,1.20]"
ordering="NONE"
side="BOTH"
